/// Flutter icons CommentIcon
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CommentIcon
///      fonts:
///       - asset: fonts/CommentIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CommentIcon {
  CommentIcon._();

  static const _kFontFam = 'CommentIcon';
  static const String? _kFontPkg = null;

  static const IconData commentcount = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
